### ISSUE TITLE
Assembly longs support

### ISSUE THREAD

**Issue by donno2048** [darijanrijan/ctoassembly#1]
Why can't it compile code using the `long` type?...

**Comment by darijanrijan** [comment]
Hi Donno,

Since the compiler is built for demonstration purposes, only the minimal set of C types and operations is implemented. Long type is sadly not supported. Here you can see what is supported: http://ctoassembly.com/microc.html

**Comment by donno2048** [comment]
Oh, thanks!
I honestly just typed in the address bar `c to assembly` to see if there are any special steps required to use longs in assembly without actually learning anything 🙄  ...
Anyway, this is an awesome project.
